In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Iris.csv')

In [4]:
import numpy as np
from sklearn import svm

 **Classification**

In [19]:
X = [[0, 0], [1, 1],[0, 1],[1, 0]]

In [20]:
Y = [0,1,0,1]

In [21]:
clf = svm.SVC()

In [22]:
clf.fit(X, Y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
k = clf.predict([[1., 0.]])
print(k)

[1]


In [14]:
# get support vectors
clf.support_vectors_

array([[0., 0.],
       [1., 1.]])

In [15]:
# get indices of support vectors
clf.support_

array([0, 1], dtype=int32)

In [16]:
# get number of support vectors for each class
clf.n_support_

array([1, 1], dtype=int32)

**Multi-class classification**

In [27]:
X = [[0], [1], [2], [3]]
Y = [0, 1, 2, 3]
clf = svm.SVC(decision_function_shape='ovo')
clf.fit(X, Y)

dec = clf.decision_function([[1]])
dec.shape[1] # 4 classes: 4*3/2 = 6

clf.decision_function_shape = "ovr"
dec = clf.decision_function([[1]])
dec.shape[1] # 4 classes

4